### ISSUE TITLE
Strong-named assemblies

### ISSUE THREAD

**Issue by sjoerd222888** [neosmart/AsyncLock#11]
Would it be possible for you to provide strong-named (signed) assemblies in your nuget package?

**Comment by sjoerd222888** [comment]
I just realized you have already added signing of assembly with commit https://github.com/neosmart/AsyncLock/commit/1ab97e8bc92fa92100ac967090cd9a53a352bd87

It has has just not yet been made available on nuget.org. Looking forward to have a signed version there :-).

**Comment by mqudsi** [comment]
Done: https://github.com/neosmart/AsyncLock/releases/tag/3.2.1
