### ISSUE TITLE
AsyncLock and DispatcherTimer

### ISSUE THREAD

**Issue by lukasf** [neosmart/AsyncLock#16]
Hi, I am using the AsyncLock and I have observed that it does not play well in the following scenario:

I have a long running async operation, triggered from the app's UI thread. The app also has a DispatcherTimer which updates status and runs frequently. To prevent cross thread issues, I have added the AsyncLock. But it does not work: I can see that the method called by the DispatcherTimer can successfully acquire the lock, although it is also held by the long running operation.

Have you seen something like this? I assume that the AsyncLock might falsely assume reentrancy, because the DispatcherTimer call comes from the same thread as the original async operation. But of course, there is no reentrancy here. The DispatcherTimer method should block until the long running operation is completed.

There does not seem to be a way to disable reentrancy for your AsyncLock, right? What do you think of the observed behavior?

**Comment by mqudsi** [comment]
Can you please post a code sample? Also, what kind of application is this (WPF, UWP, SWF, etc)?
