### ISSUE TITLE
Nested async lock and parallel execution issue

### ISSUE THREAD

**Issue by metallserge** [neosmart/AsyncLock#4]
Hi!

I've written quite stupid check for nested async locking and parallel execution  (and forgot to move asyncLock out of method!) and got deadlock after 1-2 stepping out of nested "Lock2"
upd: even after making asyncLock static readonly - issue still persist

```csharp
static void Main(string[] args)
        {
            try
            {
                Task.WhenAll(Enumerable.Range(0, 10).Select(SomeMethod)).GetAwaiter().GetResult();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            Console.WriteLine("Press any key to continue...");
            Console.ReadKey();
        }

private static async Task SomeMethod(int i)
        {
            var asyncLock = new AsyncLock();
            Console.WriteLine($"Outside {i}");
            await Task.Delay(100);
            using (await asyncLock.LockAsync())
            {
                Console.WriteLine($"Lock1 {i}");
                await Task.Delay(100);
                using (await asyncLock.LockAsync())
                {
                    Console.WriteLine($"Lock2 {i}");
                    await Task.Delay(100);
                }
            }
        }
```

Is it an issue, or I'm doing something wrong?

**Comment by mqudsi** [comment]
The problem is that the framework is resuming the task on another thread, which won't let the reentrance of the AsyncLock go through. An earlier version of the code worked around this differently by using the stack trace to determine the thread context rather than using a thread-local id (unique to each managed thread) to determine cross-thread access.

I've checked other implementations of async locks and they have the same problem.

**Comment by mysteryjeans** [comment]
I have also implemented lightweight version of AsyncLock which also supports lock reentrances. Your test works fine.. You can review source in here [Flettu](https://github.com/mysteryjeans/Flettu)

        static void Main(string[] args)
        {
            try
            {
                Console.WriteLine("Running Test 1..");
                Task.WhenAll(Enumerable.Range(0, 10).Select(SomeMethod)).GetAwaiter().GetResult();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            try
            {
                Console.WriteLine("Running Test 2..");
                using(var asyncLock = new AsyncLock())
                {
                    Task.WhenAll(Enumerable.Range(0, 10).Select(i => SomeMethod(asyncLock, i))).GetAwaiter().GetResult();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            Console.WriteLine("Press any key to continue...");
            Console.ReadKey();
        }

        private static async Task SomeMethod(AsyncLock asyncLock, int i)
        {
                Console.WriteLine($"Outside {i}");
                await Task.Delay(100);
                using (await asyncLock.AcquireAsync())
                {
                    Console.WriteLine($"Lock1 {i}");
                    await Task.Delay(100);
                    using (await asyncLock.AcquireAsync())
                    {
                        Console.WriteLine($"Lock2 {i}");
                        await Task.Delay(100);
                    }
                }
        }

        private static async Task SomeMethod(int i)
        {
            using (var asyncLock = new AsyncLock())
            {
                Console.WriteLine($"Outside {i}");
                await Task.Delay(100);
                using (await asyncLock.AcquireAsync())
                {
                    Console.WriteLine($"Lock1 {i}");
                    await Task.Delay(100);
                    using (await asyncLock.AcquireAsync())
                    {
                        Console.WriteLine($"Lock2 {i}");
                        await Task.Delay(100);
                    }
                }
            }
        }

**Comment by mqudsi** [comment]
AsyncLock 3.0 has been released which internally uses AsyncLocal to track the current execution context and handles this test case OK. I see @mysteryjeans is using a similar approach.
