### ISSUE TITLE
can't use in async void method.

### ISSUE THREAD

**Issue by a44281071** [neosmart/AsyncLock#7]
``` csharp
    private AsyncLock lll = new AsyncLock();

    private async void Button_Click(object sender, RoutedEventArgs e)
    {
      using (var l = lll.Lock())
      {
        await Task.Delay(5000);
        Trace.TraceInformation("Button_Click delay 5000");
      }
    }
```

**Comment by mqudsi** [comment]
I think you're not using the latest version of the code?

**Comment by a44281071** [comment]
In this case click. `Lock()` will get semaphore, and await task.
Then click again. `Lock()` will lock UI thread and wait semaphore release.
If I use `LockAsync()` it wait semaphore, wait 5s, trace info, wait semaphore again, wait 5s, trace info.

**Comment by mqudsi** [comment]
Are you using the latest code from `master`? Is this the newly-added synchronous `.Lock()` method?

**Comment by mqudsi** [comment]
@a44281071 please try with the latest code, also available on Nuget as `3.1.0-BETA1`
https://www.nuget.org/packages/NeoSmart.AsyncLock/3.1.0-BETA1

**Comment by mqudsi** [comment]
@a44281071 did the beta release or the latest code from git work for you?

**Comment by mqudsi** [comment]
Closing for lack of response. Feel free to reply at any point and I'll re-open.
