### ISSUE TITLE
Async locking based on key

### ISSUE THREAD

**Issue by thomasgalliker** [neosmart/AsyncLock#8]
Sometimes, I have situations where I want to lock certain areas for a particular user only (e.g. some business logic must be run in one piece for a certain user). I'm using neosmart AsyncLock in some software solutions and therefore - instead of inventing some new nugets - I was asking myself if it would be possible to extend `AsyncLock.LockAsync` method with a key parameter.

```
using (await _lock.LockAsync(userId))
{
   // Protected for User with userId
}
```

I'm not sure if you let other people touch your code (you know what I mean...) and I also have not a very clear picture of how I could integrate such a feature into AsyncLock. But I guess we could use some kind of thread-safe dictionary, which adds key-value pairs of T (generic-typed key) and value (the lock handle, some SemaphoreSlim or whatever you use in AsyncLock).

Let me know what you think about it.

**Comment by mqudsi** [comment]
Yes, this is an extremely important type of locking to support, especially in contexts where idempotency is a must (e.g. when charging an order). I actually already published a nuget for just that when .NET Core was first introduced to work around the lack of named mutexes supporting `.WaitAsync()`.

It's part of the "NeoSmart Web Toolkit" available at https://github.com/neosmart/web and [on NuGet as `NeoSmart.Web`](https://www.nuget.org/packages/NeoSmart.Web/). You want `NeoSmart.Web.ScopedMutex` ([direct link to docs](https://github.com/neosmart/web#neosmartwebscopedmutex)).

I'm pretty sure this sample is exactly what you are looking for:

```csharp
using (await ScopedMutex::CreateAsync("myguid"))
{
	// Exclusive access granted, any other calls to Create()
	// or CreateAsync() will block until `mutex` is disposed!

	foo.DoSomethingCritical();
}
```

**Comment by thomasgalliker** [comment]
Thanks for your response @mqudsi 
This is indeed what I need. The problem is, I’m using AsyncLock on all kind of platforms (Xamarin mobile apps included) and therefore I cant include your Web nuget. I copied a solution from stackoverflow, but since I already use your AsyncLock I found it bit confusing to have two locks doing almost the same thing.

**Comment by thomasgalliker** [comment]
I think we can close this one, unless you consider adding the key-based locking in NeoSmart.AsyncLock too.
Thanks for your help.

**Comment by mqudsi** [comment]
I'll publish the `ScopedMutex` to NuGet.

**Comment by mqudsi** [comment]
It's been published as `NeoSmart.Synchronization` and is available [on NuGet](https://www.nuget.org/packages/NeoSmart.Synchronization/) and [on GitHub](https://github.com/neosmart/synchronization)

**Comment by mqudsi** [comment]
Note that `AsyncLock` and `ScopedMutex` are fundamentally different under the hood (one recurses, one doesn't; one requires synchronization over a global dictionary, one doesn't).

**Comment by thomasgalliker** [comment]
Thanks for your help 👍🏽
