### ISSUE TITLE
Support cancellation token for synchronous lock method

### ISSUE THREAD

**Issue by Stroniax** [neosmart/AsyncLock#9]
Since the synchronous Lock method is calling `_parent.Wait()`, which accepts a cancellation token, please allow a cancellation token to be provided to the Lock() method.

https://github.com/neosmart/AsyncLock/blob/653b788cdd8a17c6e3615a5675b57093ffb01454/AsyncLock/AsyncLock.cs#L81-L89
```
 internal IDisposable ObtainLock(CancellationToken cancellationToken) 
 { 
     while (!TryEnter()) 
     {
         // We need to wait for someone to leave the lock before trying again. 
         _parent._retry.Wait(cancellationToken); 
     }
     return this; 
 } 
```
https://github.com/neosmart/AsyncLock/blob/653b788cdd8a17c6e3615a5675b57093ffb01454/AsyncLock/AsyncLock.cs#L205-L212

```
public IDisposable Lock(CancellationToken cancellationToken = default) 
{ 
    var @lock = new InnerLock(this, _asyncId.Value, ThreadId); 
    // Increment the async stack counter to prevent a child task from getting 
     // the lock at the same time as a child thread. 
    _asyncId.Value = Interlocked.Increment(ref AsyncLock.AsyncStackCounter); 
    return @lock.ObtainLock(cancellationToken); 
} 
```

I haven't looked very much at the code, I imagine proper disposal may also be required if the cancellation is requested.

**Comment by mqudsi** [comment]
This is included in today's non-preview AsyncLock 3.2.0 release on NuGet. @Stroniax you are mentioned in the release notes for your contribution - much appreciated!
